server:
  port: 9091

spring:
  datasource:
    name: testerDS
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/auth2?serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.query.substitutions: true 'T', false 'F'
      hibernate.jdbc.batch_size: 30
      hibernate.format_sql: true
      org.hibernate.envers.auditTableSuffix: _AUD
      org.hibernate.envers.revisionTypeFieldName: REV_TYPE
      org.hibernate.envers.doNotAuditOptimisticLockingField: false
      #      hibernate.ejb.interceptor:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
#      hibernate.cache.use_second_level_cache: true
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: false
#      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
#      hibernate.cache.hazelcast.instance_name: Ehazelcast
#      hibernate.cache.use_minimal_puts: true
#      hibernate.cache.hazelcast.use_lite_member: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy